default: &default
  adapter: postgresql
  encoding: unicode
  username: installvirtual
  password: installvirtual
  host: postgres
  port: 5432

development:
  <<: *default
  database: installvirtual_dev

test:
  <<: *default
  database: installvirtual_test

production:
  <<: *default
  database: installvirtual
