default: &default
  adapter: psql
  encoding: utf8
  username: installvirtual
  password: installvirtual
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: installvirtual_dev

test:
  <<: *default
  database: installvirtual_test

production:
  <<: *default
  database: installvirtual_prod